version: '3'

services:
  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - /home/sab/prometheus/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus
volumes:
  prom_data:
