global:
  scrape_interval: 15s
  scrape_timeout: 
  evaluation_interval: "15s"

#add alerting manager
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['192.168.1.246:80']

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['192.168.1.246:9113']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.1.246:9100']
